### ISSUE TITLE
Getting list of assets fails on testnet (succeeds in production)

### ISSUE THREAD

**Issue by tyvdh** [astroband/astrograph#185]
```
{
  assets(
    first: 10
  ) {
    nodes {
      id
      code
    }
  }
}
```

```
{
  "errors": [
    {
      "message": "relation \"assets\" does not exist",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "assets"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "relation \"assets\" does not exist",
          "name": "QueryFailedError",
          "length": 106,
          "severity": "ERROR",
          "code": "42P01",
          "position": "432",
          "file": "parse_relation.c",
          "line": "1180",
          "routine": "parserOpenTable",
          "query": "SELECT \"assets\".\"id\" AS \"assets_id\", \"assets\".\"code\" AS \"assets_code\", \"assets\".\"issuer\" AS \"assets_issuer\", \"assets\".\"totalSupply\" AS \"assets_totalSupply\", \"assets\".\"circulatingSupply\" AS \"assets_circulatingSupply\", \"assets\".\"holdersCount\" AS \"assets_holdersCount\", \"assets\".\"unauthorizedHoldersCount\" AS \"assets_unauthorizedHoldersCount\", \"assets\".\"lastActivity\" AS \"assets_lastActivity\", \"assets\".\"flags\" AS \"assets_flags\" FROM \"assets\" \"assets\" ORDER BY \"assets\".\"id\" ASC LIMIT 10",
          "parameters": [],
          "stacktrace": [
            "QueryFailedError: relation \"assets\" does not exist",
            "    at new QueryFailedError (/home/node/astrograph-server/node_modules/typeorm/error/QueryFailedError.js:11:28)",
            "    at Query.callback (/home/node/astrograph-server/node_modules/typeorm/driver/postgres/PostgresQueryRunner.js:176:38)",
            "    at Query.handleError (/home/node/astrograph-server/node_modules/pg/lib/query.js:142:17)",
            "    at Connection.connectedErrorMessageHandler (/home/node/astrograph-server/node_modules/pg/lib/client.js:211:17)",
            "    at Connection.emit (events.js:198:13)",
            "    at Connection.EventEmitter.emit (domain.js:448:20)",
            "    at Socket.<anonymous> (/home/node/astrograph-server/node_modules/pg/lib/connection.js:126:12)",
            "    at Socket.emit (events.js:198:13)",
            "    at Socket.EventEmitter.emit (domain.js:448:20)",
            "    at addChunk (_stream_readable.js:288:12)",
            "    at readableAddChunk (_stream_readable.js:269:11)",
            "    at Socket.Readable.push (_stream_readable.js:224:10)",
            "    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)"
          ]
        }
      }
    }
  ],
  "data": {
    "assets": null
  }
}
```

**Comment by charlie-wasp** [comment]
Hi @tyvdh ! It seems to work fine now, you can check it out. Feel free to reopen this issue if the error stays
