### ISSUE TITLE
Add `type` as a filter argument on the `operations` endpoint

### ISSUE THREAD

**Issue by tyvdh** [astroband/astrograph#186]
```
{
    operations (
  	first: 100
        type: "CreatePassiveSellOfferOperation"
  ) {
    nodes {
      type
    }
  }
}
```

**Comment by charlie-wasp** [comment]
@tyvdh in fact, Astrograph already supports such filter. For your example it would look like:

```
{
  operations (
    first: 100
    type: createPassiveSellOffer
  ) {
    nodes {
      type
    }
  }
}
```

**Comment by tyvdh** [comment]
I get 

```
{
  "error": {
    "errors": [
      {
        "message": "Unknown argument \"type\" on field \"operations\" of type \"Query\".",
        "extensions": {
          "code": "GRAPHQL_VALIDATION_FAILED",
          "exception": {
            "stacktrace": [
              "GraphQLError: Unknown argument \"type\" on field \"operations\" of type \"Query\".",
              "    at Object.Argument (/var/www/astrograph/source/node_modules/graphql/validation/rules/KnownArgumentNames.js:60:29)",
              "    at Object.enter (/var/www/astrograph/source/node_modules/graphql/language/visitor.js:324:29)",
              "    at Object.enter (/var/www/astrograph/source/node_modules/graphql/language/visitor.js:375:25)",
              "    at visit (/var/www/astrograph/source/node_modules/graphql/language/visitor.js:242:26)",
              "    at Object.validate (/var/www/astrograph/source/node_modules/graphql/validation/validate.js:73:24)",
              "    at validate (/var/www/astrograph/source/node_modules/apollo-server-core/dist/requestPipeline.js:212:32)",
              "    at Object.<anonymous> (/var/www/astrograph/source/node_modules/apollo-server-core/dist/requestPipeline.js:125:42)",
              "    at Generator.next (<anonymous>)",
              "    at fulfilled (/var/www/astrograph/source/node_modules/apollo-server-core/dist/requestPipeline.js:5:58)",
              "    at process._tickCallback (internal/process/next_tick.js:68:7)"
            ]
          }
        }
      }
    ]
  }
}
```

When running that query

**Comment by tyvdh** [comment]
Oddly enough it works on testnet, just not on https://demo.astrograph.io/graphql/

**Comment by charlie-wasp** [comment]
@tyvdh ah, yes, it works only on the testnet, because testnet instance uses ElasticSearch storage, so we can filter operations on our side. Pubnet instance relies on the Horizon, so we're limited by its filtering features

**Comment by tyvdh** [comment]
ETA on when pubnet will be moved to ES? Having testnet mismatched from pubnet greatly reduces the usefulness of this service. :/
