### ISSUE TITLE
Transaction query returns error when using pubnet 

### ISSUE THREAD

**Issue by ManuelaGar** [astroband/astrograph#188]
Hi! I would be really grateful if you could help me out.
1. Intended outcome: To retrieve transaction data using the transaction hash when queried.
2. Actual outcome: I get the following error:
![Captura de Pantalla 2020-02-14 a la(s) 10 57 56 a  m](https://user-images.githubusercontent.com/35504015/74547001-67a71000-4f19-11ea-8c61-9507edda5735.png)
And in the terminal: 
`error: Converting circular structure to JSON {"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["TypeError: Converting circular structure to JSON","    at JSON.stringify (<anonymous>)","    at prettyJSONStringify (/Users/mgh/Desktop/astro-stellar/astrograph/node_modules/apollo-server-core/src/runHttpQuery.ts:457:15)","    at /Users/mgh/Desktop/astro-stellar/astrograph/node_modules/apollo-server-core/src/runHttpQuery.ts:330:16","    at Generator.next (<anonymous>)","    at fulfilled (/Users/mgh/Desktop/astro-stellar/astrograph/node_modules/apollo-server-core/dist/runHttpQuery.js:5:58)","    at process._tickCallback (internal/process/next_tick.js:68:7)"]}},"timestamp":"2020-02-14T15:53:50.214Z"}`

3. How to reproduce the issue: I am using a different stellar core than what is suggested (I couldn't get the suggested one running). Here is the content of the docker-compose.yaml file:

[docker-compose.docx](https://github.com/astroband/astrograph/files/4205376/docker-compose.docx)

I already made a transaction in pubnet and tried to query for the transaction data, here is the hash: b5f34cb4031b7c35502a628b6be2f46260bb3154fea51003ed62ba950781324f

**Comment by charlie-wasp** [comment]
Hello @ManuelaGar!

I didn't try your setup yet, but looking on the screenshot you provided I can say that you provided wrong argument to the query. You provided account public key, not the transaction's hash

You can try to fix that first, and I'll try your setup soon

And thank you for trying out Astrograph! ⭐️

**Comment by ManuelaGar** [comment]
Hi @charlie-wasp,

Yes, my bad, but even with the transaction hash I get the same outcome.
![Captura de Pantalla 2020-02-15 a la(s) 2 23 33 p  m](https://user-images.githubusercontent.com/35504015/74593943-c4c8c180-4ffe-11ea-9245-d41540c42e7d.png)

Thanks for your quick response anyway, I will wait for you to try it out! :)

Also, I forgot that I added the .env file in Astrograph, here are its contents:
DATABASE_URL=postgresql://stellar:1@localhost:5432/core

**Comment by charlie-wasp** [comment]
@ManuelaGar hello again, sorry for the late reply. I decided to walk an extra mile and prepare `docker-compose` configs for you and other future users of Astrograph.

I added the [section](https://github.com/astroband/astrograph#docker-compose) in `README` about that

For the pubnet you can run the next commands:

```
docker-compose -f docker_compose/docker-compose.pubnet.yaml up -d
# wait a little for the stellar-core and postgres to start up and then run the next command
docker exec -it astrograph-stellar-core-postgres-pubnet psql -U stellar -d stellar -f /init.sql
```

The point is that Astrograph architecture has changed significantly and infrastructure around it became more complex. And we didn't reflect it in the docs (sorry about that!) 😅 So unfortunately your setup was not sufficient for Astrograph to run properly

Talking particularly about your issue, I tried on our pubnet setup and I couldn't reproduce it. You can try your query [here](https://demo.astrograph.io/graphql/)

So I would advise you to try the new setup, or if you're just interested in running queries, try our [pubnet](https://demo.astrograph.io/graphql/) and [testnet](https://testnet.astrograph.io/graphql/) sandboxes.

Also, if you're using Keybase, Astrograph has a dedicated chat there, so you can ask any questions there

**Comment by ManuelaGar** [comment]
Dear @charlie-wasp,

Wow! Thank you so much for helping me out. I am planning on running queries on the stellar network but it will be just a small part of a healthcare application I am planning on building, so thank you again for this :)

Astrograph is awesome!
